/**
 * This file was generated by CMake 3.28.1 based on EngineDefinitions.tmpl
 */

#pragma once

#define IMBER_VERSION_MAJOR 0
#define IMBER_VERSION_MINOR 0
#define IMBER_VERSION_PATCH 1

#define IMBER_VERSION_SHORT 0.0
#define IMBER_VERSION_STRING "0.0.1"

/* #undef IMBER_STATIC */
